name: Go
on:
  push: null
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5
    - name: Check Go code format
      run: "if [ -n \"$(gofmt -l .)\" ]; then\n  echo \"Go code is not formatted. Run 'go fmt' to format\
        \ your code.\"\n  exit 1\nfi\n"
    - name: Check go.mod format
      run: "if [ -n \"$(go mod tidy)\" ]; then\n  echo \"Go module is not tidied. Run 'go mod tiny' to\
        \ clean up old deps.\"\n  exit 1\nfi\n"
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5
    - name: Vet Go code
      run: go vet ./...
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test ./...
